version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - frontend-network



networks:
  frontend-network:
    driver: bridge 